### ISSUE TITLE
emu grazed - 2016 tif files for diff reflectance bands

### ISSUE THREAD

**Issue by adelegem** [traitecoevo/fowlers_veg_timeline#28]

**Comment by adrian-g-fisher** [comment]
I've made new single band images from the 2016 drone images, for conservation and emu grazed:
SPATIAL:\fowlers_gap\imagery\drone\2016\conservation_20160914
SPATIAL:\fowlers_gap\imagery\drone\2016\emugrazed_20160914

You can also use the emu images that Andres made reprocessing in Pix4D:
SPATIAL:\fowlers_gap\imagery\drone\2016\emuausplot_20160915_reprocessed

Andres tried to reprocess the conservation data, but it turned out to be from the wrong area.
